### PR TITLE
using `RichLog` instead of `ScrollView` for `TextScrollView`

### PR DESCRIPTION
**Pull request by Vipul-Cariappa**
reduces the code
better UI
enables vertical and horizontal scrolls

BEFORE:
Screenshot from 2024-10-02 16-21-44

AFTER:
image

Please look at the horizontal scroll bars.
Also, look at the misalignment I have circled.

### CODE REVIEW

**Comment by mvassilev** [comment]
Well done!

**Comment by vgvassilev** [comment]
Can you attach screenshots of before and after? Maybe improve the commit message, too?

**Comment by Vipul-Cariappa** [comment]
> Can you attach screenshots of before and after?

Done. I have edited the PR description with the screenshots.

---

> Maybe improve the commit message, too?

I don't know what I should change it to.

**Comment by vgvassilev** [comment]
> > Can you attach screenshots of before and after?
> 
> Done. I have edited the PR description with the screenshots.
> 
> > Maybe improve the commit message, too?
> 
> I don't know what I should change it to.

Something that has complete sentences? And explaining to a person without knowledge what was done.

**Comment by Vipul-Cariappa** [comment]
> Something that has complete sentences? And explaining to a person without knowledge what was done.

I have made the suggested changes. Please let me know if it requires additional changes.

**Pull request merged**
